<?php
/**
 * Посылка писем через PHP
 */

/**
 * Отправка письма
 * bool mail(string $to, string $subject, string $msg, [,string $headers])
 * Пример:
 * mail(
 *  "somebody@mail.ru", #To
 *  "Mail robot" # Subject
 *  "Hello!\nThis is autogenerated message - please do not reply."
 * )
 *
 * Если передан четвертый параметр, переданная в нем строка вставляется между концом стандартных почтовых заголовков (To, Content-Type и т.д.)
 * и началом текста письма. Обычно этот параметр используется для задания дополнительных заголовков письма.
 * mail(
 *  "somebody@mail.ru",
 *  "Mail robot",
 *  "Hello!\nThis is autogenerated message - please do not reply!.",
 *  join("\r\n", array( # другие заголовки
 *      "From: webmaster@SERVER_NAME",
 *      "Reply-to: webmaster@$SERVER_NAME",
 *      "X-Mailer: PHP/" . phpversion()
 *    )
 *  )
 * )
 */